version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - node/test:
            pkg-manager: yarn
            test-results-for: jest 
