version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - run:
          command: yarn test
          name: Run tests
workflows:
    build-and-test:
      jobs:
        - build-and-test
