import { DeviceType } from 'zigbee-herdsman/dist/adapter/tstype';
import { Device } from 'zigbee-herdsman/dist/controller/model';

const DEVICES = {
  light: {
    ID: 7,
    type: 'Router',
    ieeeAddr: '0x0000000000000000',
    networkAddress: 33948,
    manufacturerID: 4107,
    endpoints: [
      {
        ID: 11,
        profileID: 49246,
        deviceID: 528,
        inputClusters: [],
        outputClusters: [],
        deviceNetworkAddress: 33948,
        deviceIeeeAddress: '0x0000000000000001',
        clusters: [],
        binds: [],
        configuredReportings: [],
        meta: {},
      },
      {
        ID: 242,
        profileID: 41440,
        deviceID: 97,
        inputClusters: [],
        outputClusters: [],
        deviceNetworkAddress: 33948,
        deviceIeeeAddress: '0x0000000000000002',
        clusters: {},
        binds: [],
        configuredReportings: [],
        meta: {},
      },
    ],
    manufacturerName: 'Philips',
    powerSource: 'Mains (single phase)',
    modelID: 'LCT015',
    applicationVersion: 2,
    stackVersion: 1,
    zclVersion: 1,
    hardwareVersion: 2,
    dateCode: '20170908',
    softwareBuildID: '1.29.0_r21169',
    interviewCompleted: true,
    interviewing: false,
    meta: {},
    lastSeen: 1612474748836,
  },

  motionSensor: {
    ID: 8,
    type: 'EndDevice',
    ieeeAddr: '0x0000000000000003',
    networkAddress: 59864,
    manufacturerID: 4151,
    endpoints: [
      {
        ID: 1,
        profileID: 260,
        deviceID: 263,
        inputClusters: [],
        outputClusters: [],
        deviceNetworkAddress: 59864,
        deviceIeeeAddress: '0x0000000000000004',
        clusters: [],
        binds: [],
        configuredReportings: [],
        meta: {},
      },
    ],
    manufacturerName: 'LUMI',
    powerSource: 'Battery',
    modelID: 'lumi.sensor_motion.aq2',
    applicationVersion: 5,
    stackVersion: 2,
    zclVersion: 1,
    hardwareVersion: 1,
    dateCode: '20170627',
    softwareBuildID: '3000-0001',
    interviewCompleted: true,
    interviewing: false,
    meta: {},
    lastSeen: 1612619445909,
  },

  lock: {
    ID: 8,
    type: 'EndDevice',
    ieeeAddr: '0x0000000000000005',
    networkAddress: 59864,
    manufacturerID: 4151,
    endpoints: [
      {
        ID: 1,
        profileID: 260,
        deviceID: 263,
        inputClusters: [],
        outputClusters: [],
        deviceNetworkAddress: 59864,
        deviceIeeeAddress: '0x0000000000000006',
        clusters: [],
        binds: [],
        configuredReportings: [],
        meta: {},
      },
    ],
    manufacturerName: 'Yale',
    powerSource: 'Battery',
    modelID: 'YRD446 BLE TSDB',
    applicationVersion: 5,
    stackVersion: 2,
    zclVersion: 1,
    hardwareVersion: 1,
    dateCode: '20170627',
    softwareBuildID: '3000-0001',
    interviewCompleted: true,
    interviewing: false,
    meta: {},
    lastSeen: 1612619445909,
  },

  lumiLock: {
    ID: 4,
    type: 'Router',
    ieeeAddr: '0x00158d01028e2d8d',
    networkAddress: 43733,
    manufacturerID: 4151,
    endpoints: [
      {
        ID: 1,
        profileID: 260,
        deviceID: 10,
        inputClusters: [],
        outputClusters: [],
        deviceNetworkAddress: 43733,
        deviceIeeeAddress: '0x00158d0002812d8d',
        clusters: [],
        _binds: [],
        _configuredReportings: [],
        meta: {},
      },
    ],
    manufacturerName: 'LUMI',
    powerSource: 'Battery',
    modelID: 'lumi.lock.v1',
    applicationVersion: 1,
    stackVersion: 2,
    zclVersion: 0,
    hardwareVersion: 37,
    dateCode: '04-03-2018',
    softwareBuildID: undefined,
    interviewCompleted: true,
    interviewing: false,
    skipDefaultResponse: false,
    meta: {},
    lastSeen: 1614683537983,
  },

  contactSensor: {
    ID: 8,
    type: 'EndDevice',
    ieeeAddr: '0x0000000000000007',
    networkAddress: 59864,
    manufacturerID: 4151,
    endpoints: [
      {
        ID: 1,
        profileID: 260,
        deviceID: 263,
        inputClusters: [],
        outputClusters: [],
        deviceNetworkAddress: 59864,
        deviceIeeeAddress: '0x0000000000000008',
        clusters: [],
        binds: [],
        configuredReportings: [],
        meta: {},
      },
    ],
    manufacturerName: 'Xiaomi',
    powerSource: 'Battery',
    modelID: 'lumi.sensor_magnet.aq2',
    applicationVersion: 5,
    stackVersion: 2,
    zclVersion: 1,
    hardwareVersion: 1,
    dateCode: '20170627',
    softwareBuildID: '3000-0001',
    interviewCompleted: true,
    interviewing: false,
    meta: {},
    lastSeen: 1612619445909,
  },

  vibrationSensor: {
    ID: 8,
    type: 'EndDevice',
    ieeeAddr: '0x0000000000000009',
    networkAddress: 59864,
    manufacturerID: 4151,
    endpoints: [
      {
        ID: 1,
        profileID: 260,
        deviceID: 263,
        inputClusters: [],
        outputClusters: [],
        deviceNetworkAddress: 59864,
        deviceIeeeAddress: '0x0000000000000010',
        clusters: [],
        binds: [],
        configuredReportings: [],
        meta: {},
      },
    ],
    manufacturerName: 'Xiaomi',
    powerSource: 'Battery',
    modelID: 'lumi.vibration.aq1',
    applicationVersion: 5,
    stackVersion: 2,
    zclVersion: 1,
    hardwareVersion: 1,
    dateCode: '20170627',
    softwareBuildID: '3000-0001',
    interviewCompleted: true,
    interviewing: false,
    meta: {},
    lastSeen: 1612619445909,
  },

  vibrationSensor2: {
    ID: 8,
    type: 'EndDevice',
    ieeeAddr: '0x0000000000000011',
    networkAddress: 59864,
    manufacturerID: 4151,
    endpoints: [
      {
        ID: 1,
        profileID: 260,
        deviceID: 263,
        inputClusters: [],
        outputClusters: [],
        deviceNetworkAddress: 59864,
        deviceIeeeAddress: '0x0000000000000011',
        clusters: [],
        binds: [],
        configuredReportings: [],
        meta: {},
      },
    ],
    manufacturerName: '_TYZB01_3zv6oleo',
    powerSource: 'Battery',
    modelID: 'TS0210',
    applicationVersion: 5,
    stackVersion: 2,
    zclVersion: 1,
    hardwareVersion: 1,
    dateCode: '20170627',
    softwareBuildID: '3000-0001',
    interviewCompleted: true,
    interviewing: false,
    meta: {},
    lastSeen: 1612619445909,
  },

  ikeaLight: {
    ID: 7,
    type: 'Router',
    ieeeAddr: '0x0000000000000012',
    networkAddress: 30884,
    manufacturerID: 4476,
    endpoints: [
      {
        ID: 1,
        profileID: 260,
        deviceID: 257,
        inputClusters: [0, 3, 4, 5, 6, 8, 4096],
        outputClusters: [5, 25, 32, 4096],
        deviceNetworkAddress: 30884,
        deviceIeeeAddress: '0x0000000000000012',
        clusters: { genBasic: [] },
        binds: [],
        configuredReportings: [],
        meta: {},
      },
    ],
    manufacturerName: 'IKEA of Sweden',
    powerSource: 'Mains (single phase)',
    modelID: 'TRADFRI bulb GU10 WW 400lm',
    applicationVersion: 33,
    stackVersion: 99,
    zclVersion: 3,
    hardwareVersion: 2,
    dateCode: '20181203',
    softwareBuildID: '2.1.022',
    interviewCompleted: true,
    interviewing: false,
    skipDefaultResponse: false,
    meta: {},
    lastSeen: 1613115188438,
    linkquality: 26,
  },

  ikeaOnOffButton: {
    type: 'EndDevice',
    ieeeAddr: '0xccccccfffee404b7',
    networkAddress: 35876,
    manufacturerID: 4476,
    manufacturerName: 'IKEA of Sweden',
    powerSource: 'Battery',
    modelID: 'TRADFRI on/off switch',
    interviewCompleted: true,
    softwareBuildID: '2.2.008',
    lastSeen: 1614204061701,
    endpoints: [
      {
        ID: 1,
        profileID: 260,
        deviceID: 2080,
        inputClusters: [0, 1, 3, 9, 32, 4096, 64636],
        outputClusters: [3, 4, 6, 8, 25, 258, 4096],
        deviceNetworkAddress: 35876,
        deviceIeeeAddress: '0xccccccfffee404b7',
        clusters: {
          genPowerCfg: {
            attributes: {
              batteryPercentageRemaining: 34,
            },
          },
        },
        binds: [
          {
            cluster: 6,
            groupID: 901,
            type: 'group',
          },
          {
            cluster: 1,
            type: 'endpoint',
            deviceIeeeAddress: '0x00124b001cd478c0',
            endpointID: 1,
          },
        ],
        configuredReportings: [
          {
            cluster: 1,
            attrId: 33,
            minRepIntval: 3600,
            maxRepIntval: 62000,
            repChange: 0,
          },
        ],
        meta: {},
      },
    ],
    otaAvailable: true,
  },
};

export function getDevice(name: keyof typeof DEVICES): Device {
  const STRUCT = DEVICES[name];
  if (STRUCT) {
    return Device.create(
      STRUCT.type as DeviceType,
      STRUCT.ieeeAddr,
      STRUCT.networkAddress,
      STRUCT.manufacturerID,
      STRUCT.manufacturerName,
      STRUCT.powerSource,
      STRUCT.modelID,
      STRUCT.interviewCompleted,
      STRUCT.endpoints
    );
  }
  throw new Error(`Unknown device with name ${name}`);
}
